name: Memomate Server
on:
  push:
    branches: ["master"]
jobs:
  build-and-run:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Set up working directory
        run: mkdir -p ${{ secrets.WORKING_DIRECTORY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{ secrets.WORKING_DIRECTORY }}

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Where am I
        working-directory: ${{ secrets.WORKING_DIRECTORY }}
        run: pwd

      - name: Install dependencies
        working-directory: ${{ secrets.WORKING_DIRECTORY }}
        run: npm ci

      - name: Test envs
        working-directory: ${{ secrets.WORKING_DIRECTORY }}
        run: env > environment.txt
