name: Memomate Server
on:
  push:
    branches: ["master"]
jobs:
  build-and-run:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Change directory
        run: |
          WORKING_DIR="${{ secrets.WORKING_DIRECTORY }}"
          cd "${WORKING_DIR}"
          echo "Working directory changed to: $PWD"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test envs
        run: env > environment.txt
