name: Memomate Server
on:
  push:
    branches: ["master"]
jobs:
  build-and-run:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup working directory
        run: mkdir -p ${{ vars.WORKING_DIRECTORY }}

      - name: Generate .env file
        run: |
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "CORS_ORIGIN=${{ vars.CORS_ORIGIN }}" >> .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "DB_NAME=${{ vars.DB_NAME }}" >> .env
          echo "DB_LOGIN=${{ secrets.DB_LOGIN }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Sync files
        run: >
          rsync -av --delete --no-times 
          --exclude='.git/' 
          --exclude='node_modules/' 
          "$GITHUB_WORKSPACE/" "${{ vars.WORKING_DIRECTORY }}/"

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ vars.WORKING_DIRECTORY }}

      - name: Build
        run: npm run build
        working-directory: ${{ vars.WORKING_DIRECTORY }}

      - name: Restart service
        run: sudo systemctl restart ${{ vars.SERVICE_NAME }}
