name: Memomate Server
on:
  push:
    branches: ["master"]
jobs:
  build-and-run:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files
        run: |
          mkdir -p ${{ secrets.WORKING_DIRECTORY }}
          rsync -a --delete \
            --exclude='.git/' \
            --exclude='node_modules/' \
            --exclude='.env'
            "$GITHUB_WORKSPACE/" "${{ secrets.WORKING_DIRECTORY }}/"

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test envs
        run: env > environment.txt
